#parallel jobs and one additional job for second build

version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "First job"
      - run: 
          name: "Variables"
          environment:
            TESTVAR: valueoftestvar
          command: |
            echo "TRIGGERER: ${CIRCLE_USERNAME}"
            echo "BUILD_NUMBER: ${CIRCLE_BUILD_NUM}"
            echo "BUILD_URL: ${CIRCLE_BUILD_URL}"
            echo "BRANCH: ${CIRCLE_BRANCH}"
            echo "RUNNING JOB: ${CIRCLE_JOB}"
            echo "JOB PARALLELISM: ${CIRCLE_NODE_TOTAL}"
            echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
            echo 'export MYNEWVAR="Value of new var in bash_env"' >> $BASH_ENV
            source $BASH_ENV
            echo $MYNEWVAR
            echo $TESTVAR
      - run: echo $TESTVAR
      - run: echo $MYNEWVAR
      - persist_to_workspace:
          root: /
            
  test:
    steps:
      - attach_workspace:
        at: /
      - checkout
      - run: echo "Second parallel job"
      - run: echo $ENVVAR
      - run: echo $ENVVARTWO
      - run: echo $MYNEWVAR
      
      
workflows:
  version: 2
  "Context test":
    jobs:
      - build
      - test:
          context: first-content
          requires:
            - build
